In [3]:
from tqdm.notebook import tqdm

In [4]:
import re

In [5]:
import pandas as pd
import time

In [6]:
import subprocess

In [7]:
import json
import requests

## Helpers for connecting to GitHub v3 APIs

In [6]:
with open("auth_token.txt", "r") as f:
    TOKEN = f.read()

In [7]:
import requests

url = 'https://api.github.com/search/code?q='
headers = {
    'Authorization': f'Bearer {TOKEN.strip()}',
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28'
}

## Getting top 8000 package list from PyPi

In [8]:
# https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.min.json
with open("top-pypi-packages-30-days.min.json", "r") as f:
    pypi_packages = json.load(f)

In [9]:
df_pypi = pd.DataFrame(pypi_packages['rows'])

In [10]:
df_pypi.head()

   download_count            project
0       895246471              boto3
1       424262451            urllib3
2       362439956           botocore
3       324232670           requests
4       302150693  typing-extensions

In [11]:
df_pypi.sort_values(by='download_count', inplace=True, ascending=False)

In [12]:
df_pypi.head()

   download_count            project
0       895246471              boto3
1       424262451            urllib3
2       362439956           botocore
3       324232670           requests
4       302150693  typing-extensions

## Grab the github repo URL from PyPi page

In [13]:
projects = df_pypi.project.tolist()

In [14]:
PYPI_URL = 'https://pypi.org/project/{package}/'
github_repo_pattern = r'https://github\.com/([A-Za-z0-9-]+/[A-Za-z0-9-]+)'
def get_pypi_page(package):
    r = requests.get(PYPI_URL.format(package=package))
    repo = [p for p in list(set(re.findall(github_repo_pattern, r.text))) if 'pypi' not in p]
    return repo

In [16]:
PYPI_URL = 'https://pypi.org/project/{package}/'
repos = {}
for p in tqdm(projects):
    repos[p] = get_pypi_page(p)

  0%|          | 0/8000 [00:00<?, ?it/s]

In [17]:
repos

{'boto3': ['boto/boto3'],
 'urllib3': ['urllib3/urllib3'],
 'botocore': ['boto/botocore', 'boto/boto3', 'aws/aws-cli'],
 'requests': ['psf/requests'],
 'typing-extensions': ['python/typing'],
 'setuptools': ['psf/black', 'astral-sh/ruff', 'pypa/setuptools'],
 'charset-normalizer': ['jawah/niquests',
  'Ousret/charset',
  'ousret/charset',
  'jawah/wassima',
  'nickspring/charset-normalizer-rs',
  'chardet/chardet',
  'PyYoshi/cChardet'],
 'certifi': ['certifi/python-certifi'],
 's3transfer': ['boto/s3transfer'],
 'wheel': ['pypa/wheel'],
 'packaging': ['pypa/packaging'],
 'pyyaml': ['yaml/pyyaml'],
 'python-dateutil': ['dateutil/dateutil'],
 'idna': ['kjd/idna'],
 'grpcio-status': [],
 'cryptography': ['pyca/cryptography'],
 'pip': ['pypa/pip'],
 'six': ['benjaminp/six'],
 'numpy': ['numpy/numpy'],
 'google-api-core': ['googleapis/python-api-core'],
 'importlib-metadata': ['python/importlib', 'psf/black', 'astral-sh/ruff'],
 'awscli': ['aws/aws-cli'],
 'aiobotocore': ['microsoft/pyright',
  'aio-libs/aiobotocore',
  'boto/botocore',
  'aio-libs/aiohttp'],
 'zipp': ['psf/black', 'astral-sh/ruff', 'jaraco/zipp'],
 'click': ['pallets/click'],
 'cffi': ['python-cffi/cffi'],
 'protobuf': [],
 'fsspec': ['fsspec/filesystem'],
 'pytz': ['stub42/pytz'],
 'pandas': ['stub42/pytz', 'pandas-dev/pandas'],
 's3fs': ['fsspec/s3fs'],
 'markupsafe': ['pallets/markupsafe'],
 'pyasn1': ['pyasn1/pyasn1-modules',
  'kimgr/asn1ate',
  'pyasn1/pyasn1',
  'epyasn1/pyasn1'],
 'rsa': ['sybrenstuvel/python-rsa'],
 'pyjwt': ['jpadilla/pyjwt'],
 'jmespath': ['jmespath/jmespath'],
 'pydantic': ['willmcgugan/rich',
  'sponsors/samuelcolvin',
  'python/typeshed',
  'pydantic/pydantic-core',
  'pydantic/pydantic',
  'python/cpython'],
 'attrs': ['sponsors/hynek', 'python-attrs/attrs', 'microsoft/pyright'],
 'platformdirs': ['platformdirs/platformdirs', 'ActiveState/appdirs'],
 'colorama': ['tartley/colorama'],
 'googleapis-common-protos': ['googleapis/python-api-common-protos',
  'googleapis/googleapis'],
 'werkzeug': ['pallets/werkzeug'],
 'pycparser': ['eliben/pycparser'],
 'google-auth': ['googleapis/google-auth-library-python'],
 'jinja2': ['pallets/jinja'],
 'virtualenv': ['pypa/virtualenv', 'psf/black'],
 'cachetools': ['psf/black', 'python/typeshed', 'tkem/cachetools'],
 'filelock': ['psf/black', 'tox-dev/py-filelock'],
 'flask': ['pallets/flask'],
 'jsonschema': ['python-jsonschema/jsonschema',
  'python-jsonschema/check-jsonschema',
  'sponsors/Julian'],
 'sqlalchemy': ['sqlalchemy/sqlalchemy'],
 'pluggy': ['pytest-dev/pluggy', 'ambv/black'],
 'tomli': ['hukkin/mdformat-toc',
  'hukkin/tomli',
  'sdispater/tomlkit',
  'hukkin/tomli-w',
  'toml-lang/compliance'],
 'exceptiongroup': ['agronholm/exceptiongroup'],
 'pyparsing': ['pyparsing/pyparsing'],
 'async-timeout': ['aio-libs/async-timeout'],
 'pytest': ['pytest-dev/pytest', 'psf/black'],
 'docutils': [],
 'soupsieve': ['facelessuser/soupsieve'],
 'aiohttp': ['aio-libs/aiohttp-demos',
  'python-attrs/attrs',
  'python/asyncio',
  'aio-libs/aiohttp'],
 'oauthlib': ['requests/requests-oauthlib',
  'tilgovi/pyramid-oauthlib',
  'singingwolfboy/flask-dance',
  'lepture/flask-oauthlib',
  'requests/requests',
  'thomsonreuters/bottle-oauthlib',
  'evonove/django-oauth-toolkit',
  'oauthlib/oauthlib'],
 'pyarrow': ['apache/arrow'],
 'psutil': ['rust-psutil/rust-psutil',
  'ajenti/ajenti',
  'aristocratos/bpytop',
  'home-assistant/home-assistant',
  'shirou/gopsutil',
  'google/grr',
  'facebook/osquery',
  'sponsors/giampaolo',
  'Jahaja/psdash',
  'hamon-in/cpslib',
  'nicolargo/glances',
  'giampaolo/psutil',
  'johnscillieri/psutil-nim'],
 'grpcio': ['grpc/grpc'],
 'greenlet': ['python-greenlet/greenlet'],
 'requests-oauthlib': ['requests/requests-oauthlib'],
 'isodate': ['gweis/isodate'],
 'tqdm': ['pypa/twine',
  'casperdcl/git-fame',
  'tqdm/tqdm',
  'niltonvolpato/python-progressbar',
  'vinta/awesome-python'],
 'wrapt': ['GrahamDumpleton/wrapt'],
 'lxml': ['lxml/lxml'],
 'beautifulsoup4': [],
 'frozenlist': ['aio-libs/frozenlist'],
 'azure-core': ['Azure/azure-sdk-for-python'],
 'coverage': ['sponsors/nedbat', 'nedbat/coveragepy'],
 'pillow': ['python-pillow/Pillow'],
 'pyasn1-modules': ['pyasn1/pyasn1', 'kimgr/asn1ate', 'pyasn1/pyasn1-modules'],
 'pygments': ['pygments/pygments'],
 'pyopenssl': ['pyca/cryptography', 'pyca/pyopenssl'],
 'importlib-resources': ['python/importlib', 'psf/black', 'astral-sh/ruff'],
 'distlib': ['pypa/distlib'],
 'multidict': ['aio-libs/multidict'],
 'yarl': ['aio-libs/multidict', 'aio-libs/yarl'],
 'scipy': ['scipy/scipy'],
 'iniconfig': ['pytest-dev/iniconfig', 'RonnyPfannschmidt/iniconfig'],
 'websocket-client': ['bubbleboy14/registeredeventlistener',
  'websocket-client/websocket-client'],
 'et-xmlfile': [],
 'openpyxl': [],
 'aiosignal': ['aio-libs/aiosignal'],
 'asn1crypto': ['wbond/ocspbuilder',
  'wbond/certbuilder',
  'wbond/asn1crypto',
  'wbond/certvalidator',
  'wbond/csrbuilder',
  'wbond/oscrypto',
  'wbond/crlbuilder'],
 'google-cloud-storage': ['googleapis/python-storage',
  'googleapis/google-cloud-python'],
 'tomlkit': ['LeopoldArkham/Molten', 'sdispater/tomlkit'],
 'google-cloud-core': ['googleapis/python-cloud-core'],
 'requests-toolbelt': ['kennethreitz/requests', 'requests/toolbelt'],
 'chardet': ['chardet/chardet', 'sigmavirus24/charade'],
 'msgpack': ['msgpack/msgpack-python'],
 'deprecated': ['tantale/deprecated'],
 'more-itertools': ['more-itertools/more-itertools'],
 'decorator': ['micheles/decorator'],
 'google-resumable-media': ['googleapis/google-resumable-media-python'],
 'tabulate': ['astanin/python-tabulate', 'pyenv/pyenv'],
 'pydantic-core': ['flamegraph-rs/flamegraph',
  'sponsors/samuelcolvin',
  'pydantic/pydantic-core'],
 'itsdangerous': ['pallets/itsdangerous'],
 'tzlocal': ['regebro/tzlocal'],
 'gitpython': ['python-security/pyt',
  'msiemens/PyGitUp',
  'bthayer2365/git-gud',
  'wdm0006/git-pandas',
  'kivy/kivy-designer',
  'Byron/gitoxide',
  'gitpython-developers/GitPython',
  'gitpython-developers/gitdb',
  'nettitude/Prowl',
  'axitkhurana/buster',
  'OmniLayer/omniwallet',
  'BeayemX/GitViper',
  'ezyang/git-ftp',
  'Neo23x0/Loki',
  'ishepard/pydriller',
  'mseclab/PyJFuzz'],
 'msal': ['AzureAD/microsoft-authentication-library-for-python'],
 'wcwidth': ['aperezdc/lua-wcwidth',
  'saulpw/visidata',
  'peterbrittain/asciimatics',
  'fumiyas/wcwidth-cjk',
  'dbcli/pgcli',
  'jquast/wcwidth',
  'janlelis/unicode-display',
  'thomasballinger/curtsies',
  'joachimschmidt557/zig-wcwidth',
  'astanin/python-tabulate',
  'stratis-storage/stratis-cli',
  'selectel/pyte',
  'nbedos/termtosvg',
  'bluebear94/Terminal-WCWidth',
  'python-cmd2/cmd2',
  'prompt-toolkit/python-prompt-toolkit',
  'grepsuzette/wcwidth',
  'mattn/go-runewidth',
  'jquast/ucs-detect',
  'joshuarubin/wcwidth9',
  'jquast/blessed',
  'landscapeio/prospector',
  'timoxley/wcwidth',
  'alecrabbit/php-wcwidth',
  'ihabunek/toot',
  'rspeer/python-ftfy'],
 'pymysql': ['PyMySQL/PyMySQL'],
 'rpds-py': ['sponsors/Julian',
  'bowtie-json-schema/bowtie',
  'crate-py/rpds',
  'python-jsonschema/referencing'],
 'psycopg2-binary': ['psycopg/psycopg2'],
 'pynacl': ['jedisct1/libsodium', 'pyca/pynacl'],
 'smmap': ['gitpython-developers/smmap'],
 'proto-plus': ['googleapis/proto-plus-python'],
 'paramiko': ['paramiko/paramiko'],
 'azure-storage-blob': ['Azure/azure-sdk-for-python'],
 'google-auth-oauthlib': ['idan/oauthlib',
  'GoogleCloudPlatform/google-auth-library-python-oauthlib',
  'googleapis/google-auth-library-python-oauthlib',
  'googleapis/google-auth-library-python'],
 'referencing': ['sponsors/Julian', 'python-jsonschema/referencing'],
 'jsonschema-specifications': ['python-jsonschema/jsonschema-specifications',
  'sponsors/Julian'],
 'pathspec': ['highb/pathspec-ruby',
  'cpburnz/python-path-specification',
  'cpburnz/python-pathspec'],
 'scikit-learn': ['psf/black', 'scikit-learn/scikit-learn'],
 'anyio': ['agronholm/anyio', 'python-trio/trio'],
 'bcrypt': ['pyca/bcrypt'],
 'matplotlib': ['matplotlib/matplotlib'],
 'poetry-core': ['psf/black',
  'python-poetry/poetry',
  'python-poetry/poetry-core'],
 'portalocker': ['wolph/portalocker',
  'AzureAD/microsoft-authentication-extensions-for-python',
  'WoLpH/portalocker'],
 'annotated-types': ['annotated-types/annotated-types', 'tiangolo/fastapi'],
 'keyring': ['psf/black',
  'astral-sh/ruff',
  'scop/bash-completion',
  'jaraco/keyrings',
  'jaraco/keyring'],
 'grpcio-tools': ['grpc/grpc'],
 'kiwisolver': ['nucleic/kiwi'],
 'regex': ['mrabarnett/mrab-regex'],
 'joblib': ['tomMoral/loky', 'joblib/joblib'],
 'gitdb': ['gitpython-developers/gitdb'],
 'jaraco-classes': ['astral-sh/ruff', 'psf/black', 'jaraco/jaraco'],
 'pycryptodomex': ['Legrandin/pycryptodome'],
 'pytest-cov': ['jazzband/pip-tools',
  'pytest-dev/pytest-cov',
  'nedbat/coveragepy',
  'python/cpython'],
 'pyrsistent': ['boxed/instar',
  'tobgu/pyrsistent',
  'mingmingrr/pyrsistent-extras'],
 'mypy-extensions': ['python/mypy'],
 'cycler': ['matplotlib/cycler'],
 'tzdata': ['python/tzdata'],
 'dill': ['uqfoundation/dill'],
 'markdown-it-py': ['markdown-it/markdown-it',
  'executablebooks/markdown-it-py',
  'ambv/black'],
 'pexpect': [],
 'ptyprocess': ['pexpect/ptyprocess'],
 'sqlparse': ['andialbrecht/sqlparse'],
 'docker': ['docker/docker-py'],
 'azure-identity': ['Azure/azure-sdk-for-python',
  'AzureAD/microsoft-authentication-library-for-python'],
 'msrest': ['Azure/azure-sdk-for-python',
  'Azure/autorest',
  'Azure/msrest-for-python'],
 'ruamel-yaml': ['indygreg/PyOxidizer'],
 'snowflake-connector-python': ['platformdirs/platformdirs',
  'snowflakedb/snowflake-connector-python',
  'urllib3/urllib3'],
 'babel': ['python-babel/babel'],
 'sniffio': ['python-trio/sniffio'],
 'tenacity': ['jd/tenacity'],
 'ruamel-yaml-clib': [],
 'fonttools': ['googlefonts/colr-gradients-spec',
  'fonttools/skia-pathops',
  'unified-font-objects/ufoLib',
  'typesupply/ufo2svg',
  'googlei18n/fontmake',
  'googlei18n/ufo2ft',
  'googlei18n/cu2qu',
  'adobe-type-tools/aots',
  'googlefonts/cu2qu',
  'LettError/designSpaceDocument',
  'fonttools/fonttools',
  'harfbuzz/boring-expansion-spec'],
 'cython': ['cython/cython'],
 'google-api-python-client': ['httplib2/httplib2',
  'sigmavirus24/uritemplate',
  'googleapis/google-api-python-client',
  'googleapis/google-cloud-python',
  'firebase/firebase-admin-python',
  'googleads/google-ads-python'],
 'backoff': ['litl/backoff'],
 'azure-common': ['Azure/azure-sdk-for-python'],
 'py4j': [],
 'awswrangler': ['psf/black', 'aws/aws-sdk-pandas'],
 'google-cloud-bigquery': ['googleapis/google-cloud-python',
  'googleapis/python-bigquery'],
 'scramp': ['efficks/passlib',
  'cagdass/scrampy',
  'tlocke/pg8000',
  'tlocke/scramp'],
 'prompt-toolkit': ['jquast/wcwidth', 'prompt-toolkit/python-prompt-toolkit'],
 'sagemaker': ['aws/sagemaker-python-sdk',
  'aws/sagemaker-sparkml-serving-container',
  'combust/mleap',
  'python/black'],
 'msal-extensions': ['AzureAD/microsoft-authentication-extensions-for-python',
  'AzureAD/microsoft-authentication-library-for-python',
  'Azure-Samples/ms-identity-python-webapp'],
 'google-crc32c': ['pypa/manylinux',
  'google/crc32c',
  'googleapis/python-crc32c'],
 'threadpoolctl': ['joblib/threadpoolctl',
  'jeremiedbb/Nested',
  'xianyi/OpenBLAS',
  'IntelPython/smp'],
 'cachecontrol': ['psf/cachecontrol', 'httplib2/httplib2'],
 'rich': ['textualize/rich',
  'Textualize/rich',
  'Textualize/textual',
  'textualize/rich-cli'],
 'future': [],
 'markdown': ['Python-Markdown/markdown'],
 'poetry-plugin-export': ['python-poetry/poetry-plugin-export'],
 'google-auth-httplib2': ['GoogleCloudPlatform/google-auth-library-python-httplib2',
  'GoogleCloudPlatform/google-auth-library-python',
  'httplib2/httplib2'],
 'py': ['pytest-dev/py'],
 'nest-asyncio': ['erdewit/nest'],
 'alembic': ['sqlalchemy/alembic'],
 'redis': ['redis/redis-py', 'redis/redis', 'redis/redis-om-python'],
 'gunicorn': ['benoitc/gunicorn'],
 'dnspython': ['rthalley/dnspython', 'psf/black'],
 'pg8000': ['tlocke/pg8000'],
 'httplib2': ['httplib2/httplib2'],
 'cloudpickle': ['cloudpipe/cloudpickle'],
 'traitlets': ['psf/black', 'ipython/traitlets'],
 'python-dotenv': ['joke2k/django-environ',
  'sloria/environs',
  'naorlivne/parse',
  'HBNetwork/python-decouple',
  'jpadilla/django-dotenv',
  'jezdez/django-configurations',
  'sergeyklay/django-environ-2',
  'theskumar/python-dotenv',
  'nickstenning/honcho',
  'rochacbruno/dynaconf',
  'sobolevn/dump-env'],
 'shellingham': ['sarugaku/shellingham'],
 'trove-classifiers': ['pypa/trove-classifiers'],
 'jedi': ['tkf/emacs-jedi',
  'davidhalter/jedi-vim',
  'DamnWidget/anaconda',
  'abingham/emacs-ycmd',
  'maralla/completor',
  'muffinmad/anakin-language-server',
  'ycm-core/YouCompleteMe',
  'Kozea/wdb',
  'srusskih/SublimeJEDI',
  'jorgenschaefer/elpy',
  'syohex/emacs-company-jedi',
  'palantir/python-language-server',
  'typeddjango/django-stubs',
  'isamert/gedi',
  'zchee/deoplete-jedi',
  'proofit404/anaconda-mode',
  'python-lsp/python-lsp-server',
  'pappasam/jedi-language-server',
  'davidhalter/jedi',
  'lawrenceakka/python-jedi'],
 'networkx': ['networkx/networkx'],
 'rapidfuzz': ['maxbachmann/RapidFuzz',
  'maxbachmann/rapidfuzz',
  'seatgeek/fuzzywuzzy'],
 'uvicorn': ['pgjones/hypercorn',
  'django/daphne',
  'sponsors/encode',
  'encode/uvicorn'],
 'redshift-connector': ['sqlalchemy-redshift/sqlalchemy-redshift',
  'vaab/gitchangelog',
  'pandas-dev/pandas',
  'numpy/numpy',
  'pinterest/querybook',
  'apache/airflow',
  'aws/amazon-redshift-python-driver'],
 'tornado': ['tornadoweb/tornado'],
 'blinker': ['pallets-eco/blinker'],
 'ply': [],
 'ipython': ['ipython/ipython'],
 'pycodestyle': ['PyCQA/pycodestyle'],
 'xmltodict': ['martinblech/xmltodict'],
 'marshmallow': ['ambv/black', 'marshmallow-code/marshmallow'],
 'h11': ['nodejs/http-parser', 'python-hyper/h11'],
 'termcolor': ['termcolor/termcolor', 'psf/black'],
 'toml': ['uiri/toml', 'BurntSushi/toml-test', 'toml-lang/toml'],
 'uritemplate': ['python-hyper/uritemplate'],
 'pyspark': ['apache/spark'],
 'oscrypto': ['wbond/ocspbuilder',
  'wbond/certbuilder',
  'wbond/asn1crypto',
  'wbond/certvalidator',
  'wbond/csrbuilder',
  'wbond/oscrypto',
  'wbond/crlbuilder'],
 'dulwich': ['dulwich/dulwich'],
 'pycryptodome': ['Legrandin/pycryptodome'],
 'setuptools-scm': ['pypa/setuptools'],
 'mccabe': ['pycqa/mccabe'],
 'sortedcontainers': ['python-trio/trio',
  'dask/distributed',
  'angr/angr',
  'grantjenks/python-sortedcontainers',
  'quantopian/zipline'],
 'jsonpath-ng': ['kennknowles/python-jsonpath-ng',
  'dabeaz/ply',
  'h2non/jsonpath-ng',
  'kennknowles/python-jsonpath-rw'],
 'absl-py': ['abseil/abseil-py'],
 'jeepney': [],
 'poetry': ['python-poetry/poetry-plugin-export',
  'python-poetry/cleo',
  'python-poetry/poetry-core',
  'python-poetry/poetry-plugin-bundle',
  'python-poetry/install',
  'python-poetry/poetry',
  'python-poetry/website'],
 'secretstorage': ['mitya57/secretstorage'],
 'pyodbc': ['mkleehammer/pyodbc'],
 'requests-aws4auth': ['sam-washington/requests-aws4auth',
  'kennethreitz/requests',
  'tedder/requests-aws4auth'],
 'defusedxml': ['psf/black',
  'tiran/defusedexpat',
  'tiran/expat',
  'tiran/defusedxml'],
 'contourpy': ['contourpy/contourpy'],
 'webencodings': ['SimonSapin/python-webencodings',
  'gsnedders/python-webencodings'],
 'black': ['psf/black',
  'psf/black-pre-commit-mirror',
  'mypyc/mypyc',
  'cooperlees/black-primer',
  'python/peps'],
 'httpx': ['encode/httpx'],
 'pyzmq': ['zeromq/pyzmq', 'zeromq/libzmq'],
 'mako': ['sqlalchemy/mako'],
 'prometheus-client': ['prometheus/client',
  'prometheus/pushgateway',
  'prometheus/node'],
 'mdurl': ['markdown-it/mdurl', 'executablebooks/mdurl'],
 'httpcore': ['encode/httpcore', 'encode/httpx'],
 'bs4': [],
 'jsonpointer': ['stefankoegl/python-json-pointer'],
 'pkginfo': [],
 'isort': ['psf/black', 'pycqa/isort'],
 'pkgutil-resolve-name': ['graingert/pkgutil-resolve-name'],
 'opensearch-py': ['opensearch-project/opensearch-py'],
 'python-utils': ['WoLpH/python-utils'],
 'typing-inspect': ['ilevkivskyi/typing'],
 'pytest-runner': ['psf/black',
  'pypa/setuptools',
  'pytest-dev/pytest',
  'pytest-dev/pytest-runner',
  'jsonpickle/jsonpickle'],
 'pymongo': ['mongodb/specifications'],
 'build': ['pypa/build'],
 'huggingface-hub': ['huggingface/huggingface'],
 'loguru': ['Delgan/loguru',
  'Qix-/better-exceptions',
  'erezinman/loguru-config',
  'notifiers/notifiers'],
 'pyflakes': ['PyCQA/pyflakes'],
 'tensorboard': ['tensorflow/tensorboard'],
 'adal': ['AzureAD/azure-activedirectory-library-for-python',
  'AzureAD/microsoft-authentication-library-for-python'],
 'apache-airflow': ['apache/airflow', 'bazelbuild/rules', 'psf/black'],
 'argcomplete': ['kislyuk/argcomplete'],
 'jupyter-core': ['jupyter/jupyter'],
 'flake8': ['PyCQA/flake8', 'pycqa/flake8', 'sponsors/asottile'],
 'progressbar2': ['WoLpH/python-progressbar'],
 'xlrd': [],
 'sentry-sdk': ['getsentry/sentry-python', 'getsentry/raven-python'],
 'parso': ['davidhalter/jedi', 'davidhalter/parso'],
 'jupyter-client': ['jupyter/jupyter'],
 'datadog': ['DataDog/datadog-api-client-python', 'DataDog/datadogpy'],
 'databricks-cli': ['databricks/databricks-sdk-py',
  'databricks/databricks-cli',
  'databricks/cli'],
 'nbconvert': ['jupyter/nbconvert-examples', 'jupyter/nbconvert'],
 'arrow': ['psf/black', 'arrow-py/arrow', 'psf/requests', 'moment/moment'],
 'simplejson': ['simplejson/simplejson'],
 'pickleshare': ['pickleshare/pickleshare'],
 'toolz': ['pytoolz/toolz', 'pytoolz/cytoolz'],
 'fastapi': ['JoshData/python-email-validator',
  'swagger-api/swagger-ui',
  'tiangolo/fastapi',
  'pgjones/hypercorn',
  'ijl/orjson',
  'OAI/OpenAPI-Specification',
  'Rebilly/ReDoc',
  'deepset-ai/haystack',
  'esnme/ultrajson'],
 'python-json-logger': [],
 'backcall': ['takluyver/backcall'],
 'aenum': ['ethanfurman/aenum'],
 'websockets': ['python-websockets/websockets'],
 'pyproject-hooks': ['pypa/build', 'pypa/pyproject-hooks'],
 'tensorflow': ['tensorflow/tensorflow'],
 'transformers': ['suno-ai/bark',
  'google/flax',
  'tanreinama/GPTSAN',
  'google-research/text-to-text-transfer-transformer',
  'google-research/t5x',
  'EleutherAI/gpt-neo',
  'google/jax',
  'huggingface/transformers',
  'BlinkDL/RWKV-LM',
  'huggingface/huggingface',
  'mosaicml/llm-foundry',
  'kingoflolz/mesh-transformer-jax'],
 'astroid': ['pylint-dev/astroid', 'ambv/black'],
 'asgiref': ['django/asgiref', 'andrewgodwin/frequensgi', 'django/channels'],
 'pylint': ['PyCQA/bandit',
  'psf/black',
  'omegacen/pylint-sonarjson',
  'microsoft/pyright',
  'ambv/black',
  'myint/autoflake',
  'DanielNoord/pydocstringformatter',
  'facebook/pyre-check',
  'pylint-dev/pylint-django',
  'python/mypy',
  'asottile/pyupgrade',
  'pylint-dev/pylint',
  'PyCQA/flake8',
  'charliermarsh/ruff'],
 'asttokens': ['gristlabs/asttokens', 'PyCQA/astroid'],
 'google-cloud-pubsub': ['googleapis/google-cloud-python',
  'googleapis/python-pubsub'],
 'matplotlib-inline': ['ipython/matplotlib-inline'],
 'zope-interface': ['zopefoundation/zope'],
 'executing': ['alexmojaki/executing',
  'samuelcolvin/python-devtools',
  'alexmojaki/heartrate',
  'gruns/icecream',
  'alexmojaki/sorcery',
  'friendly-traceback/friendly-traceback',
  'getsentry/sentry-python',
  'gristlabs/asttokens',
  'alexmojaki/pure',
  'alexmojaki/stack',
  'alexmojaki/snoop',
  'pwwang/python-varname',
  'ipython/ipython'],
 'imageio': ['imageio/imageio'],
 'starlette': ['encode/starlette-example',
  'encode/starlette',
  'django/daphne',
  'sponsors/encode'],
 'aioitertools': ['omnilib/aioitertools'],
 'fastjsonschema': ['horejsek/python-fastjsonschema'],
 'google-cloud-bigquery-storage': ['googleapis/google-cloud-python',
  'googleapis/python-bigquery-storage'],
 'stack-data': ['alexmojaki/executing', 'alexmojaki/pure', 'alexmojaki/stack'],
 'jsonpatch': ['stefankoegl/python-json-patch', 'json-patch/json-patch-tests'],
 'appdirs': ['twall/jna'],
 'cattrs': ['psf/black',

In [18]:
m = []
for k in repos.keys():
    m.append({'name': k, 'repos': repos[k]})

In [19]:
df_repos = pd.DataFrame(m)

In [21]:
df_repos['repo_count'] = df_repos.repos.apply(lambda x: len(x))

In [22]:
def main_repo(row):
    repos = row['repos']
    name = row['name']
    if len(repos) == 1:
        return repos[0]

    fil = [x for x in repos if name in x]
    if len(fil) == 1:
        return fil[0]
    return None

In [23]:
df_repos['main_repo'] = df_repos.apply(main_repo, axis=1)

In [24]:
df_repos.to_csv('pypi_top.csv')

In [25]:
repos = df_repos.main_repo.dropna().tolist()

In [28]:
len(repos)

5670

## Filter the repos which make use of bandit
- This makes use of GitHub v3 APIs to find the text `bandit` in the code

In [ ]:
results = []
for repo in tqdm(repos):
    q = 'bandit+in:file+repo:{repo}'
    r = requests.get(url=url+q.format(repo=repo), headers=headers)
    if r.status_code == 403:
        print(f"Got response: {r.text}\nSleeping")
        time.sleep(65)
        print(f"Woke up")
        r = requests.get(url=url+q.format(repo=repo), headers=headers)

    # print(f"Got response: {r.text}")
    x = json.loads(r.text)
    results.extend(x['items'])

  0%|          | 0/424 [00:00<?, ?it/s]

Got response: {"message":"API rate limit exceeded for user ID 16104456. If you reach out to GitHub Support for help, please include the request ID 63F4:5F0C:574903:B40327:6548210A.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
Sleeping

In [36]:
df = pd.json_normalize(results, sep='_')

In [37]:
df.head()

,name,path,sha,url,git_url,html_url,score,repository_id,repository_node_id,repository_name,...,repository_merges_url,repository_archive_url,repository_downloads_url,repository_issues_url,repository_pulls_url,repository_milestones_url,repository_notifications_url,repository_labels_url,repository_releases_url,repository_deployments_url
0,devcontainer.json,.devcontainer/devcontainer.json,d83f255db449e790abcb7617ce7ad0fe70e9118b,https://api.github.com/repositories/65826230/c...,https://api.github.com/repositories/65826230/g...,https://github.com/taynaud/python-louvain/blob...,1.0,65826230,MDEwOlJlcG9zaXRvcnk2NTgyNjIzMA==,python-louvain,...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...,https://api.github.com/repos/taynaud/python-lo...
1,CONTRIBUTING.md,CONTRIBUTING.md,e1775ee03d0aad78ee6dc2033781146b7eb8905e,https://api.github.com/repositories/605682586/...,https://api.github.com/repositories/605682586/...,https://github.com/di/id/blob/ba260c01d5021943...,1.0,605682586,R_kgDOJBn7mg,id,...,https://api.github.com/repos/di/id/merges,https://api.github.com/repos/di/id/{archive_fo...,https://api.github.com/repos/di/id/downloads,https://api.github.com/repos/di/id/issues{/num...,https://api.github.com/repos/di/id/pulls{/number},https://api.github.com/repos/di/id/milestones{...,https://api.github.com/repos/di/id/notificatio...,https://api.github.com/repos/di/id/labels{/name},https://api.github.com/repos/di/id/releases{/id},https://api.github.com/repos/di/id/deployments
2,Makefile,Makefile,aa45ecb5f78c6343c1fd607d7d83da0e8af5076b,https://api.github.com/repositories/605682586/...,https://api.github.com/repositories/605682586/...,https://github.com/di/id/blob/ba260c01d5021943...,1.0,605682586,R_kgDOJBn7mg,id,...,https://api.github.com/repos/di/id/merges,https://api.github.com/repos/di/id/{archive_fo...,https://api.github.com/repos/di/id/downloads,https://api.github.com/repos/di/id/issues{/num...,https://api.github.com/repos/di/id/pulls{/number},https://api.github.com/repos/di/id/milestones{...,https://api.github.com/repos/di/id/notificatio...,https://api.github.com/repos/di/id/labels{/name},https://api.github.com/repos/di/id/releases{/id},https://api.github.com/repos/di/id/deployments
3,ambient.py,id/_internal/oidc/ambient.py,eadfb8118efa319cc61e0becfc5d3fb01c488358,https://api.github.com/repositories/605682586/...,https://api.github.com/repositories/605682586/...,https://github.com/di/id/blob/ba260c01d5021943...,1.0,605682586,R_kgDOJBn7mg,id,...,https://api.github.com/repos/di/id/merges,https://api.github.com/repos/di/id/{archive_fo...,https://api.github.com/repos/di/id/downloads,https://api.github.com/repos/di/id/issues{/num...,https://api.github.com/repos/di/id/pulls{/number},https://api.github.com/repos/di/id/milestones{...,https://api.github.com/repos/di/id/notificatio...,https://api.github.com/repos/di/id/labels{/name},https://api.github.com/repos/di/id/releases{/id},https://api.github.com/repos/di/id/deployments
4,pyproject.toml,pyproject.toml,a19eb4f6c3ef1795c80c408924665bab36f2ce09,https://api.github.com/repositories/605682586/...,https://api.github.com/repositories/605682586/...,https://github.com/di/id/blob/ba260c01d5021943...,1.0,605682586,R_kgDOJBn7mg,id,...,https://api.github.com/repos/di/id/merges,https://api.github.com/repos/di/id/{archive_fo...,https://api.github.com/repos/di/id/downloads,https://api.github.com/repos/di/id/issues{/num...,https://api.github.com/repos/di/id/pulls{/number},https://api.github.com/repos/di/id/milestones{...,https://api.github.com/repos/di/id/notificatio...,https://api.github.com/repos/di/id/labels{/name},https://api.github.com/repos/di/id/releases{/id},https://api.github.com/repos/di/id/deployments

In [38]:
df.to_csv('v3_filter_bandit_pypi_8k_items.csv')

## Clone the repos

In [8]:
df = pd.read_csv('v3_filter_bandit_pypi_8k_items.csv')

In [9]:
df['repo_url'] = df.apply(lambda x: 'https://github.com/' + x['repository_full_name'], axis=1)

In [10]:
len(df.repository_full_name.unique())

283

In [11]:
ignore_repo_list = [
    'https://github.com/PyCQA/bandit'
]

In [12]:
repo_urls = [r for r in df['repo_url'].unique().tolist() if r not in ignore_repo_list]

In [13]:
len(repo_urls)

282

In [ ]:
for url in repo_urls:
    print(f"Fetching {url}")
    subprocess.call("git clone --depth 1 {}".format(url), cwd='repos_pypi')

## Find all instances of nosec

In [1]:
# Run the following command
# rg "nosec" -n -g "*.py" ./repos_pypi 2>&1 | tee nosec_logs.txt